// Icon names for the app
export const ICONS = {
  audio: 'Mic',
  video: 'Video',
  meme: 'Image',
  play: 'Play',
  pause: 'Pause',
  stop: 'Square',
  volumeUp: 'VolumeX',
  volumeDown: 'Volume1',
  speedUp: 'TimerReset',
  speedDown: 'Timer',
  effects: 'Wand2',
  library: 'Library',
  recent: 'Clock',
  favorites: 'Heart',
  ai: 'Bot',
  record: 'Mic',
  videoRecord: 'Video',
  memeSelect: 'Image',
};